version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=app
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=app

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app

  app:
    build: .
    #ports:
      #- "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./app:/go/src/app/
    working_dir: "/go/src/app/"
    restart: on-failure:5
    environment:
      - LANG=C.UTF-8
      - TERM=xterm
